version: "3"

services:
  keycloak:
    build: .
    container_name: keycloak-11-theme
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:        
      - 8080:8080
    volumes: 
      - ./themes/poc:/opt/jboss/keycloak/themes/poc 